pool:
  name: Hosted Windows 2019 with VS2019

variables:
  BuildConfiguration: 'IdentityServer_Release'

trigger:
  batch: true
  branches:
    include: [master]
  paths:
    include: [IdentityServer]

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    arguments: '--configuration $(BuildConfiguration)'
  timeoutInMinutes: 10

- task: PublishBuildArtifacts@1
