pool:
  name: Hosted Windows Container
variables:
  BuildConfiguration: 'IdentityServer_Release'

trigger:
  batch: true
  branches:
    include: [master]
  paths:
    include: [IdentityServer]

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    arguments: '--configuration $(BuildConfiguration) /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true'
  timeoutInMinutes: 10
